# Generated by Django 5.0.4 on 2024-04-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
